vich_uploader:
    db_driver: orm

    mappings:
       annonces:
           uri_prefix: /images/annonces
           upload_destination: '%kernel.project_dir%/public/images/annonces'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true